# SPDX-FileCopyrightText: Copyright 2025-2026 The Secureblue Authors
#
# SPDX-License-Identifier: Apache-2.0

name: build

permissions: {}

on:
  workflow_dispatch: # allow manually triggering builds

# Cancels running workflows if a new workflow run for
# the same workflow is started
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  silverblue-main:
    name: Build silverblue main
    permissions:
      contents: read # Needed to pull the repo for the build
      actions: read # Needed to read actions and actions logs for provenance generation
      packages: write # Needed to publish images
      id-token: write # Needed for token generation for signing
    uses: ./.github/workflows/build-one-recipe.yml
    with:
      recipe: general/recipe-silverblue-main.yml
      rechunk: false
    secrets:
      SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
      KERNEL_PRIVKEY: ${{ secrets.KERNEL_PRIVKEY }}

  silverblue-main-sealed:
    name: Build silverblue main sealed
    needs: silverblue-main
    permissions:
      contents: read # Needed to pull the repo for the build
      actions: read # Needed to read actions and actions logs for provenance generation
      packages: write # Needed to publish images
      id-token: write # Needed for token generation for signing
    uses: ./.github/workflows/build-sealed-image.yml
    with:
      image: ${{ needs.silverblue-main.outputs.IMAGE_NAME }}
      base_tag: ${{ needs.silverblue-main.outputs.IMAGE_TAG }}
      base_digest: ${{ needs.silverblue-main.outputs.IMAGE_DIGEST }}
      image_version: ${{ needs.silverblue-main.outputs.IMAGE_VERSION }}
    secrets:
      COSIGN_KEY: ${{ secrets.SIGNING_SECRET }}
      UKI_DB_KEY: ${{ secrets.UKI_DB_KEY }}
